name: "Page Generator Action"
description: "Generates pages and deploys them."
runs:
  using: "composite"
  steps:
    - name: Run Page Generator
      shell: bash
      run: |
        echo "Running page generator..."
        bash ./scripts/generate-site.sh "$BUCKET_NAME" "$CONFIG"
